name: Foodhub CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      CI: ""
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node and npm
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Install backend dependencies
      run: |
        cd backend  
        npm install
        
     # Deploy the application to Netlify
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './frontend/build'  # Adjust this path based on your actual project structure
        
