name: Foodhub CI/CD
on: 
  push:
    branches:
    - master
    pull_request:
    - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run:
        cd frontend
        npm i
        npm run build
        cd backend
        npm i

      
    